env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
  - 'prettier'
rules: {
  'vue/multi-word-component-names': 'off',
  'no-non-null-assertion': 'off',
}